"""Pi extension integration for Honcho."""

import json
import shutil
from pathlib import Path
from typing import Optional

from rich.console import Console

from honcho_pi.config import Settings

console = Console()


class PiIntegrationError(Exception):
    """Pi integration error."""
    pass


# Template for Pi extension TypeScript
HONCHO_TS_TEMPLATE = '''// Honcho Extension for Pi
// Auto-generated by honcho-pi

interface HonchoConfig {
  enabled: boolean;
  apiUrl: string;
  workspace: string;
  userId: string;
  agentId: string;
}

const HONCHO_CONFIG: HonchoConfig = {
  enabled: true,
  apiUrl: "http://localhost:{port}",
  workspace: "{workspace}",
  userId: "{user_id}",
  agentId: "{agent_id}"
};

// Extension hooks for Pi
export function onObservationCreate(data: any) {
  // Send observation to Honcho API
  fetch(`${{HONCHO_CONFIG.apiUrl}}/v1/sessions/.../messages`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data)
  });
}}

export function onBeforeResponse(context: any) {
  // Retrieve context from Honcho before LLM call
  return fetch(`${{HONCHO_CONFIG.apiUrl}}/peers/${{HONCHO_CONFIG.agentId}}/chat`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({{
      query: context.input,
      agentic: true
    }})
  }}).then(r => r.json());
}}

export default HONCHO_CONFIG;
'''


DEFAULT_HONCHO_SETTINGS = {
    "honcho": {
        "enabled": True,
        "api_url": "http://localhost:8333",
        "hooks": {
            "observation_create": True,
            "before_response": True,
            "after_response": True
        },
        "commands": {
            "obs-status": "Check Honcho observation status",
            "obs-sync": "Force observation sync"
        }
    }
}


class PiIntegration:
    """Manages Pi extension integration."""
    
    def __init__(self, settings: Optional[Settings] = None):
        """Initialize Pi integration.
        
        Args:
            settings: Honcho Pi settings instance
        """
        self.settings = settings or Settings.from_env()
    
    def is_pi_installed(self) -> bool:
        """Check if Pi is installed."""
        pi_dir = self.settings.pi_agent_dir
        return pi_dir.exists() and (pi_dir / "settings.json").exists()
    
    def get_pi_settings_path(self) -> Path:
        """Get path to Pi settings.json."""
        return self.settings.pi_agent_dir / "settings.json"
    
    def get_honcho_extension_path(self) -> Path:
        """Get path where honcho.ts should be installed."""
        return self.settings.pi_extensions_dir / "honcho.ts"
    
    def read_pi_settings(self) -> dict:
        """Read current Pi settings."""
        settings_path = self.get_pi_settings_path()
        if not settings_path.exists():
            return {}
        
        try:
            with open(settings_path) as f:
                return json.load(f)
        except json.JSONDecodeError as e:
            raise PiIntegrationError(f"Invalid JSON in Pi settings: {e}")
    
    def write_pi_settings(self, settings: dict, backup: bool = True):
        """Write Pi settings.
        
        Args:
            settings: Dictionary to write
            backup: Whether to backup existing file
        """
        settings_path = self.get_pi_settings_path()
        
        # Ensure directory exists
        settings_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Backup existing settings
        if backup and settings_path.exists():
            backup_path = settings_path.with_suffix(".json.backup")
            shutil.copy2(settings_path, backup_path)
            console.print(f"[dim]Backed up existing settings to {backup_path}[/dim]")
        
        # Write new settings
        with open(settings_path, "w") as f:
            json.dump(settings, f, indent=2)
        
        console.print(f"[dim]Wrote Pi settings to {settings_path}[/dim]")
    
    def merge_honcho_settings(self, settings: Optional[dict] = None) -> dict:
        """Merge Honcho settings into Pi settings.
        
        Args:
            settings: Existing Pi settings or None to read from file
            
        Returns:
            Merged settings dictionary
        """
        if settings is None:
            settings = self.read_pi_settings()
        
        # Merge Honcho settings
        merged = settings.copy()
        
        # Update with current configuration
        honcho_config = DEFAULT_HONCHO_SETTINGS["honcho"].copy()
        honcho_config["api_url"] = f"http://localhost:{self.settings.api_port}"
        
        if "honcho" in merged:
            # Update existing
            merged["honcho"].update(honcho_config)
        else:
            # Add new
            merged["honcho"] = honcho_config
        
        return merged
    
    def generate_honcho_ts(self) -> str:
        """Generate honcho.ts extension content."""
        return HONCHO_TS_TEMPLATE.format(
            port=self.settings.api_port,
            workspace=os.getenv("HONCHO_WORKSPACE", "default"),
            user_id=os.getenv("USER", "default"),
            agent_id=os.getenv("HONCHO_AGENT_ID", "agent-honcho-pi")
        )
    
    def install_extension(self) -> bool:
        """Install Honcho extension to Pi.
        
        Returns:
            True if successful
        """
        if not self.is_pi_installed():
            raise PiIntegrationError(
                f"Pi not found at {self.settings.pi_agent_dir}. "
                "Please install Pi first."
            )
        
        # Ensure extensions directory exists
        self.settings.pi_extensions_dir.mkdir(parents=True, exist_ok=True)
        
        # Install extension file
        extension_path = self.get_honcho_extension_path()
        extension_content = self.generate_honcho_ts()
        
        with open(extension_path, "w") as f:
            f.write(extension_content)
        
        console.print(f"[green]✓ Installed extension to {extension_path}[/green]")
        
        # Merge settings
        merged_settings = self.merge_honcho_settings()
        self.write_pi_settings(merged_settings)
        
        console.print("[green]✓ Updated Pi settings.json[/green]")
        return True
    
    def uninstall_extension(self) -> bool:
        """Remove Honcho extension from Pi.
        
        Returns:
            True if successful
        """
        extension_path = self.get_honcho_extension_path()
        
        if extension_path.exists():
            extension_path.unlink()
            console.print(f"[green]✓ Removed {extension_path}[/green]")
        
        # Remove from settings
        settings = self.read_pi_settings()
        if "honcho" in settings:
            del settings["honcho"]
            self.write_pi_settings(settings)
            console.print("[green]✓ Removed Honcho from Pi settings[/green]")
        
        return True
    
    def validate_extension(self) -> list[str]:
        """Validate Pi extension installation.
        
        Returns:
            List of validation errors (empty if valid)
        """
        errors = []
        
        if not self.is_pi_installed():
            errors.append("Pi is not installed")
            return errors
        
        # Check extension file
        extension_path = self.get_honcho_extension_path()
        if not extension_path.exists():
            errors.append(f"Extension not found at {extension_path}")
        
        # Check settings
        settings = self.read_pi_settings()
        if "honcho" not in settings:
            errors.append("Honcho not configured in Pi settings.json")
        elif not settings["honcho"].get("enabled", False):
            errors.append("Honcho is disabled in Pi settings")
        
        # Check if API is accessible
        try:
            import urllib.request
            api_url = settings.get("honcho", {}).get("api_url", f"http://localhost:{self.settings.api_port}")
            req = urllib.request.Request(f"{api_url}/health", method="GET")
            with urllib.request.urlopen(req, timeout=2) as response:
                if response.status != 200:
                    errors.append(f"Honcho API not responding at {api_url}")
        except Exception as e:
            errors.append(f"Cannot connect to Honcho API: {e}")
        
        return errors
    
    def restart_pi(self) -> bool:
        """Restart Pi to pick up extension changes.
        
        Returns:
            True if successful
        """
        console.print("[dim]Restarting Pi to load extension changes...[/dim]")
        
        try:
            # Try pkill first
            import subprocess
            result = subprocess.run(
                ["pkill", "-f", "pi-mono"],
                capture_output=True
            )
            
            # Wait for restart
            import time
            time.sleep(3)
            
            console.print("[green]✓ Pi restart signal sent[/green]")
            console.print("[dim]Note: Pi will auto-restart if using supervisor/systemd[/dim]")
            return True
        except Exception as e:
            console.print(f"[yellow]⚠ Could not restart Pi: {e}[/yellow]")
            console.print("[dim]Please restart Pi manually[/dim]")
            return False


# Convenience functions
def install_pi_extension(settings: Optional[Settings] = None) -> bool:
    """Install Pi extension (convenience function)."""
    integration = PiIntegration(settings)
    return integration.install_extension()


def uninstall_pi_extension(settings: Optional[Settings] = None) -> bool:
    """Uninstall Pi extension (convenience function)."""
    integration = PiIntegration(settings)
    return integration.uninstall_extension()


def check_pi_status(settings: Optional[Settings] = None) -> dict:
    """Check Pi extension status.
    
    Returns:
        Dictionary with status information
    """
    integration = PiIntegration(settings)
    
    if not integration.is_pi_installed():
        return {
            "installed": False,
            "extension_present": False,
            "settings_configured": False,
            "errors": ["Pi not installed"]
        }
    
    errors = integration.validate_extension()
    extension_path = integration.get_honcho_extension_path()
    settings = integration.read_pi_settings()
    
    return {
        "installed": True,
        "extension_present": extension_path.exists(),
        "settings_configured": "honcho" in settings,
        "errors": errors,
        "api_url": settings.get("honcho", {}).get("api_url")
    }